// Generated by CoffeeScript 1.6.2
var Rakeshed, rakeshed,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Rakeshed = (function() {
  function Rakeshed(options) {
    this.options = options;
    this.loadTasks = __bind(this.loadTasks, this);
  }

  Rakeshed.prototype.loadTasks = function() {
    return $.ajax({
      url: "http://localhost:" + this.options.port + "/sheds",
      dataType: 'json',
      success: function(tasks) {
        var template;

        template = window.Handlebars.templates['tasks_index'](tasks);
        console.log(template);
        $('body .content').empty().append(template);
        return $('a').click(function(event) {
          var url;

          url = $(this).attr('href');
          return $.ajax({
            url: url,
            success: function(response) {
              var status_text;

              if (response.errors != null) {
                status_text = response.errors;
              } else {
                status_text = 'Sucess';
                chrome.tabs.reload();
              }
              $('#status').empty().append(status_text);
              if (response.errors == null) {
                return window.close();
              }
            }
          });
        });
      }
    });
  };

  return Rakeshed;

})();

rakeshed = new Rakeshed({
  port: 3000
});

rakeshed.loadTasks();

window.rakeshed = rakeshed;
